stages:
    - build-test-all

arch:
    image: archlinux/base
    stage: build-test-all
    before_script:
        - pacman --noconfirm -Syu base-devel clang python
    script:
        - make CC=gcc clean all test
        - make CC=clang clean all test

debian-stable:
    image: debian:stable
    stage: build-test-all
    before_script:
        - apt-get update
        - apt-get -y install build-essential clang libssl-dev openssl
    script:
        - make CC=gcc clean all test
        - make CC=clang clean all test

ubuntu-trusty:
    image: ubuntu:trusty
    stage: build-test-all
    before_script:
        - apt-get update
        - apt-get -y install build-essential clang libssl-dev openssl
    script:
        - make CC=gcc clean all test
        - make CC=clang clean all test

ubuntu-xenial:
    image: ubuntu:xenial
    stage: build-test-all
    before_script:
        - apt-get update
        - apt-get -y install build-essential clang libssl-dev openssl
    script:
        - make CC=gcc clean all test
        - make CC=clang clean all test

ubuntu-latest:
    image: ubuntu:latest
    stage: build-test-all
    before_script:
        - apt-get update
        - apt-get -y install build-essential clang libssl-dev openssl
    script:
        - make CC=gcc clean all test
        - make CC=clang clean all test
