stages:
  - Build
  - Test

.build-generic:
  stage: Build
  script:
    - make CC=gcc clean all test
    - make CC=clang clean all test
  artifacts:
    paths:
      - sand-leek
    expire_in: 1 year

.build-debian-derived:
  extends: .build-generic
  before_script:
    - apt-get update
    - apt-get -y install build-essential clang libssl-dev openssl python

Arch Linux:
  image: archlinux/base
  extends: .build-generic
  before_script:
    - pacman --noconfirm --needed -Syu base-devel clang python

Debian (stable):
  image: debian:stable
  extends: .build-debian-derived

Ubuntu (Bionic):
  image: ubuntu:bionic
  extends: .build-debian-derived

Ubuntu (Focal):
  image: ubuntu:focal
  extends: .build-debian-derived

Shellcheck:
  image: archlinux/base
  stage: Test
  before_script:
    - pacman --noconfirm --needed -Syu shellcheck
  script:
    - ./test/run-shellcheck.sh
  needs: []
